/** Shared prompt contract for raw navigation evidence and derived research rows. */
export const PER_LOT_RECEIPT_LOOP = `## PER-LOT RECEIPT LOOP — DO THIS BEFORE DATA

For every lot, repeat this compact loop and resume from saved receipts:
1. Inspect source identity first: capture the UTC opening clock before navigating to the source page, then its settled observation clock and description evidence. Read the source description and relevant physical photo descriptors before choosing or crediting a query.
2. Before every search or photo navigation, persist a raw opening receipt with the source identity, requested URL, and current UTC open clock.
3. Immediately after the page/photo is settled and inspected, persist the settled UTC observed clock plus a literal visible fact or query-specific result reference.
4. Before the next navigation, derive and save the attemptLedger/photoReviews row from that receipt. Never reconstruct clocks or observations from a batch timestamp, URL, or summary.
5. Status rules: exact zero uses outcome \`executed\`, observedStatus \`empty\`, and count 0; positive results use outcome \`executed\`, observedStatus \`settled\`, and a positive count; an uncertain/loading/error/parse gap uses outcome \`deferred\`, observedStatus \`loading\`, \`error\`, or \`parse-gap\`, and a null count. \`deferred\` is an outcome, not an observedStatus. Preserve both clocks and the raw receipt for every real attempt.
6. Set applicabilityConfirmed true only when the source description and/or inspected source photos establish the query's product identity, variant, condition, and quantity. Otherwise keep it false and uncredited.
7. Continue from saved receipts until every lot and required photo has a recorded outcome; unattempted/deferred work remains incomplete.

<!-- SAMPLE/PLACEHOLDER ONLY: shape, not observed evidence. Replace every value with the copied source receipt. -->
\`\`\`json
{"actionID":"SAMPLE_ACTION_ID","sourceID":"PLACEHOLDER_SOURCE_ID","requestURL":"https://example.invalid/SAMPLE_QUERY","openclock":"SAMPLE_UTC_OPEN_CLOCK","observedclock":"SAMPLE_UTC_SETTLED_CLOCK","visibleFact":"SAMPLE_VISIBLE_FACT","ref":"SAMPLE_REFERENCE"}
\`\`\`
`;

export const PHOTO_EVIDENCE_INTERPRETATION_INSTRUCTION = `For every gallery note, anchor the observation to the copied sourceId, ordinal, and exact photo descriptor; expand the original photo before accepting ambiguous model text, counts, or packaged contents. Count only visibly distinct objects. Distinguish packaging from contents and seller-stated materials from observed claims. Contact sheets may triage photos but cannot resolve unreadable labels.`;

export const EVIDENCE_OUTPUT_CONTRACT = `## Evidence Output Contract

Before every navigation or image-open action, persist a raw action-log row with actionID, sourceID, requestURL, and the actual UTC openclock. Immediately after the visual inspection or settled search, persist that action's actual UTC observedclock, literal photo-specific visible fact or query-specific result evidence, and an inspectable ref before any next navigation. The ref must identify retained evidence specific to that action, such as its screenshot or saved response, not a generic browser tab ID. Keep the raw action log separate from the derived attemptLedger/photoReviews; validate both against the copied source IDs and photo descriptors before completion. A self-written validation summary is not a validator result; automated imports must also reconcile the raw action log. If no persistent file is available, append the same rows to an incremental message or table. A downloaded or opened image that was not visually inspected remains pending; never manufacture clocks, access failures, or generic facts after the fact, and never claim completion while pending work remains.

${PHOTO_EVIDENCE_INTERPRETATION_INSTRUCTION}

Retain source/search responses below the tool's actual output limit. Store the tool-returned native DOM/accessibility text, HTML, or screenshot separately from the authored action summary, or include that unaltered native payload in its receipt. A JSON file containing only clocks, URLs and visibleFact is the action summary, not retained native page evidence. Do not write replacement HTML from your interpretation. A terminal [Truncated] marker, omitted rows, or incomplete pagination is not complete evidence. Preserve the rejected capture; do not delete its marker or reconstruct missing HTML from summarized rows. If an accessible settled response is too large, retain bounded chunks of the same observed DOM, verifying unchanged URL, selected Sold tab, row count, length and content fingerprint across chunks before concatenation. Save the complete sanitized response and chunk references; never include account navigation, cookies, tokens or authorization headers. Record actual displayed condition filters rather than assuming all conditions. Reconcile rendered rows, parsed rows and next-page controls. If complete retention cannot be established, keep the attempt incomplete/parse-gap instead of inferring zero results or a valuation.

For each numeric paid comp, retain the native sold evidence that establishes it, not only a written summary or parsed row. Bind the exact eBay item ID to the selected Sold surface, paid item-price column, total sold count, sold date, currency and that receipt's actual observation clock. A Seller Hub row with total sold greater than one is an average, not one transaction's paid amount. A matching number in the title, shipping, total sales or another row cannot establish the item price or single-sale count. Keep shipping separate. Preserve the Sold-search capture clock and any later original-listing inspection clock separately; never rewrite either to make them equal. An authored JSON row, screenshot filename or narrative assertion without retained native evidence remains an unverified reference, not a valuation comp.

Retained proof refs may use an action-specific screenshot://, image://, artifact://, or proof:// reference, or the actual path of its saved screenshot/response file. Use a URI only when the tool supplied a durable reference that another reader can resolve; never invent screenshot://action-001 from an action ID. For a search or source-description observation, a saved sanitized action-specific DOM/accessibility response is acceptable when a durable screenshot reference is unavailable. A successful photo review requires retained image pixels: save the inspected original image or the screenshot bytes immediately and use its actual path or durable tool image reference. A self-authored text/JSON note is not photo proof, even when it repeats a visibleFact. Without retainable image evidence, keep that photo review incomplete and give it no verified-photo credit; never invent an accessFailure if the image was accessible. A source/search URL, generic window description, or invented pointer is not retained proof. Source-review rows must preserve their raw clocks and visible facts. Original sold-proof rows must preserve the raw observed clock and page evidence; when openedAt or a retained proof reference is supplied on the proof, it must also match the original-item raw receipt. Structural validation alone does not establish that a file exists, its pixels support the observation, or its displayed price was paid.

Use these exact keys and shapes. All example values are fictional; never copy them as observed clocks, refs, URLs, IDs, or visible facts. Replace them only with copied source values and evidence actually collected at each action. The raw action log uses actionID, sourceID, requestURL, openclock, observedclock, visibleFact, and ref:

\`\`\`
{"actionID":"action-001","sourceID":"lot-001","requestURL":"https://www.ebay.com/sch/i.html?_nkw=sample&LH_Sold=1&LH_Complete=1","openclock":"2026-10-01T14:00:00.000Z","observedclock":"2026-10-01T14:00:03.000Z","visibleFact":"Sold + Completed heading shows 3 results","ref":"evidence/SAMPLE-action-001.json"}
\`\`\`

For a photo review, use the copied descriptor's exact field names. Copy fullResolutionUrl byte-for-byte from that descriptor; do not retype or normalize it. Bind the requested URL once from the parsed DATA descriptor and reuse that same string in the navigation receipt and derived row; compare all three strings before saving. Do not substitute the final redirected URL or drop parameters such as wt=false. The product-specific evidence key is visibleFact, never productSpecificVisibleFact:

\`\`\`
{"sourceId":"lot-001","ordinal":1,"fullResolutionUrl":"https://images.example.test/stilllife/lot-001-01.jpg","openedAt":"2026-10-01T14:00:10.000Z","observedAt":"2026-10-01T14:00:12.000Z","visibleFact":"Front label visibly reads Sample 2000","proofRef":"evidence/SAMPLE-photo-001.png","accessFailure":null}
\`\`\`

An unattempted search may use executedQuery: null and may carry a separate nonblank plannedQuery, but it earns no execution credit and must contain no actual URL, clock, result count, or content proof. Omit plannedQuery when absent; never emit plannedQuery: null:

\`\`\`
{"sourceId":"lot-002","attemptId":"attempt-002","queryGroupId":"query:sample-unattempted","executedQuery":null,"plannedQuery":"sample unattempted","displayedQuery":null,"outcome":"unattempted","attemptSource":"ebay-public-sold","actualQueryUrl":null,"finalUrl":null,"attemptedAt":null,"observedAt":null,"observedStatus":"unattempted","observedResultCount":null,"contentObservationRef":null,"applicabilityConfirmed":false}
\`\`\`

A challenged search is a real attempt, not an empty result. Derive its accessBlockedReason and accessObservation from the actually observed challenge. Keep contentObservationRef as the literal observation and proofRef as a retained artifact path. Do not emit a null plannedQuery or an invented browser:// proof pointer. This fictional blocked-row shape is valid only after replacing every sample value with actual receipts:

\`\`\`
{"sourceId":"lot-003","attemptId":"attempt-003","queryGroupId":"query:sample-blocked","executedQuery":"sample blocked","displayedQuery":null,"outcome":"blocked-after-attempt","attemptSource":"ebay-public-sold","actualQueryUrl":"https://www.ebay.com/sch/i.html?_nkw=sample%20blocked&LH_Sold=1&LH_Complete=1","finalUrl":"https://www.ebay.com/splashui/challenge","attemptedAt":"2026-10-01T14:01:00.000Z","observedAt":"2026-10-01T14:01:03.000Z","observedStatus":"access-blocked","observedResultCount":null,"contentObservationRef":"Checking your browser before you access eBay remained visible on the challenge page.","proofRef":"evidence/SAMPLE-blocked-003.json","accessBlockedReason":"browser-challenge","accessObservation":"Checking your browser before you access eBay remained visible on the challenge page.","applicabilityConfirmed":true}
\`\`\`

Read each clock at the action itself with new Date().toISOString() immediately before and after the awaited navigation or inspection. These are already ISO UTC readings: copy them as returned, without local-time conversion, offset arithmetic, rounding, or reusing a batch/write timestamp. Keep the exact submitted URL and observed URL in their existing derived fields; never rewrite a URL to make it look consistent.

Save a machine-readable checkpoint object containing attemptLedger, photoReviews, one aggregate photoAudit, and soldProof, in addition to the separate raw action log. Separate row arrays are useful incremental files but are not the complete checkpoint object. Proof filenames must include their actual directory path and a supported evidence extension (.png, .jpg, .webp, .json, .html, .txt, or .ndjson). For downloaded img.axd images, retain the actual image bytes under their decoded image type's extension rather than .axd. The raw ref and derived proofRef must be the same exact saved path; a bare photo-001.axd or source-001-dom.json filename is not a resolvable proof path.

Map raw sourceID to derived sourceId, openclock to attemptedAt for searches or openedAt for photos, and observedclock to observedAt without changing the readings. For searches, copy raw visibleFact unchanged into contentObservationRef: despite its name, that field contains the literal query-specific observation, not a screenshot URI or filename. Store the retained file/tool reference separately as proofRef, copied from raw ref. For photos, copy raw visibleFact unchanged into visibleFact and raw ref into proofRef. This mapping also applies to challenged searches: preserve the actually visible challenge text as the observation, not a generic loading claim. Every attempted row, including deferred, requires both clocks. If either reading is missing, retain the real attempt's available observations, URLs, and null missing clock in an invalid/incomplete checkpoint requiring re-observation. Do not relabel a real attempt unattempted, invent a time, or claim a null-clock deferred row validates. Record any new observation as a separate actual attempt; preserve the original failed checkpoint.

Save each actual action exactly once. A corrected URL or reopened photo is a new action with new clock readings and its own retained proof. Keep the original mistaken requestURL unchanged, even when it differs from the copied photo descriptor; do not rewrite the failed receipt into a successful one. Bind a photoReviews row only to the action that actually inspected its exact descriptor URL. A raw action with no valid descriptor binding stays in the log as an incomplete/rejected action, rather than being duplicated or assigned another action's clocks. Derive narrative photo counts from the final reconciled rows, not an earlier estimate.

Preserve the existing attemptLedger fields and enums exactly. An unattempted search row uses outcome: unattempted and observedStatus: unattempted. It may use executedQuery: null (or preserve legacy nonblank text), with an optional nonblank plannedQuery; actualQueryUrl, finalUrl, attemptedAt, observedAt, observedResultCount, and contentObservationRef are all null, and applicabilityConfirmed remains false. Do not place a planned URL or planned time in an unattempted row. An unvisited photo is pending, not a null-timestamp placeholder; use accessFailure only for an actually observed inability to access that copied photo. Unattempted or pending work keeps the checkpoint incomplete.

If one research surface presents a persistent access challenge, preserve the actual challenged attempt and stop requests to that challenged surface; do not bypass the challenge or repeatedly retry it. A separate signed-in Seller Hub Product Research Sold surface may receive one bounded normal-UI attempt only when independently available and authorized, as specified by the research instructions; never assume access, request credentials, or use it to evade the challenged surface. If it is also unavailable or challenged, stop there and leave remaining searches unattempted. Continue accessible source-lot pages, physical-photo review, description/identity checks, and independent research providers for every remaining selected source ID. A blocked eBay search does not make an AuctionNinja or HiBid photo inaccessible. Searches not actually attempted remain unattempted; never copy one challenged attempt onto other lots or invent per-lot blocked outcomes. Keep affected sold evidence unresolved and the overall result explicitly incomplete while completing all independent work that remains possible.
`;
